name: Build Game with Steam Runtime Sniper

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner with Ubuntu
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest  # Official Sniper SDK container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out your repository code

      - name: Install dependencies
        run: |
          #apt-get update
          #apt-get install -y build-essential  # Add any additional dependencies your game needs

      - name: Configure build
        run: |
          # Example for CMake; adjust based on your build system
          #cmake -S . -B build

      - name: Build game
        run: |
          # Example for CMake; adjust based on your build system
          # cmake --build build --config Release
          make

      - name: Package game
        run: |
          mkdir -p dist  # Create a distribution directory
          cp sdl2-blocks dist/  # Copy the executable (replace 'your_game_executable' with actual name)
          cp -r assets dist/  # Copy the assets directory
          cd dist
          zip -r ../game-package.zip .  # Create a zip file containing executable and assets

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-package
          path: game-package.zip  # Upload the zip file as an artifact
