name: Build Game for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install sdl2 sdl2-image sdl2-ttf sdl2-mixer --triplet x64-mingw-static

      - name: Debug vcpkg installation
        run: |
          dir vcpkg\installed\x64-mingw-static\include\SDL2
          dir vcpkg\installed\x64-mingw-static\lib
          dir vcpkg\installed\x64-mingw-static\bin

      - name: Build game
        env:
          SDL2_INCLUDE_DIR: vcpkg\installed\x64-mingw-static\include
          SDL2_LIB_DIR: vcpkg\installed\x64-mingw-static\lib
        run: |
          # Create build directories first
          mkdir build
          mkdir build\src
          mkdir build\src\State
          Write-Host "Number of processors: $env:NUMBER_OF_PROCESSORS"
          $jobs = if (-not $env:NUMBER_OF_PROCESSORS) { 4 } else { $env:NUMBER_OF_PROCESSORS }
          Write-Host "Jobs set to: $jobs"
          Write-Host "CXXFLAGS: -I$env:SDL2_INCLUDE_DIR -std=gnu++1z -g -fPIE -w -MMD -MP"
          Write-Host "LDFLAGS: -L$env:SDL2_LIB_DIR -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -pie"
          mingw32-make "-j$jobs" CXXFLAGS="-I$env:SDL2_INCLUDE_DIR -std=gnu++1z -g -fPIE -w -MMD -MP" LDFLAGS="-L$env:SDL2_LIB_DIR -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -pie"

      - name: Package game
        run: |
          mkdir dist
          copy sdl2-blocks.exe dist\
          xcopy assets dist\assets\ /E /H /C /I
          copy vcpkg\installed\x64-mingw-static\bin\*.dll dist\
          cd dist
          7z a ..\sdl2-blocks-windows.zip .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdl2-blocks-windows
          path: sdl2-blocks-windows.zip