name: Build Game for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: cdce28d2d7b4adb84a32ed5f8956997cc0e04710

      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
  
      - name: Download assets archive file.
        run: |
          curl -L -o Ablockalypse-Background-Music.zip "https://ablockalypse-assets.s3.us-west-2.amazonaws.com/Ablockalypse-Background-Music.zip"
          ren Ablockalypse-Background-Music.zip assets.zip

      - name: Extract assets
        run: |
          Expand-Archive -Path assets.zip -DestinationPath temp_assets/ -Force
          Remove-Item -Path assets.zip

      - name: Copy assets to assets folder
        run: |
          New-Item -Path assets -ItemType Directory -Force
          Copy-Item -Path temp_assets\assets\* -Destination assets\ -Recurse -Force
          Remove-Item -Path temp_assets\ -Recurse -Force
      
      - name: Debug MinGW Installation
        run: |
          dir "C:\mingw64\bin" || echo "MinGW bin directory not found"
          dir "C:\mingw64\bin\*.dll" || echo "No DLLs found in MinGW bin"

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-mixer[mpg123] --triplet x64-mingw-dynamic

      - name: Debug vcpkg libs and dependencies
        run: |
          dir vcpkg\installed\x64-mingw-dynamic\lib
          dir vcpkg\installed\x64-mingw-dynamic\bin
          objdump -p vcpkg\installed\x64-mingw-dynamic\bin\SDL2_image.dll | findstr "DLL Name" > sdl2_image_deps.txt
          type sdl2_image_deps.txt

      - name: Build game
        env:
          SDL2_INCLUDE_DIR: vcpkg\installed\x64-mingw-dynamic\include
          SDL2_LIB_DIR: vcpkg\installed\x64-mingw-dynamic\lib
        run: |
          mkdir build
          mkdir build\src
          mkdir build\src\State
          $jobs = if (-not $env:NUMBER_OF_PROCESSORS) { 4 } else { $env:NUMBER_OF_PROCESSORS }
          mingw32-make "-j$jobs" CXXFLAGS="-I$env:SDL2_INCLUDE_DIR -std=gnu++1z -g -fPIE -w -MMD -MP -DSDL_MAIN_HANDLED -DFULL_ASSETS" LDFLAGS="-L$env:SDL2_LIB_DIR -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lmpg123 -lshlwapi -lz -lpng16"

      - name: Package game
        run: |
          mkdir dist
          copy sdl2-blocks.exe dist\
          xcopy assets dist\assets\ /E /H /C /I
          # Core SDL2 and related DLLs
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_image.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_ttf.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_mixer.dll" dist\
          # JPEG support DLLs
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libjpeg-62.dll" dist\
          # Other dependencies
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libmpg123.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libzlib1.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libpng16.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libfreetype.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libwavpack-1.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libvorbisfile.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libbrotlidec.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libbz2.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libvorbis.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libogg.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libbrotlicommon.dll" dist\
          # MinGW runtime DLLs (required, fail if missing)
          copy "C:\mingw64\bin\libgcc_s_seh-1.dll" dist\
          copy "C:\mingw64\bin\libstdc++-6.dll" dist\
          copy "C:\mingw64\bin\libwinpthread-1.dll" dist\

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdl2-blocks-windows
          path: dist/