name: Build Game for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install sdl2 sdl2-image sdl2-ttf sdl2-mixer[mpg123] --triplet x64-mingw-dynamic

      - name: Debug vcpkg libs
        run: |
          dir vcpkg\installed\x64-mingw-dynamic\lib
          dir vcpkg\installed\x64-mingw-dynamic\bin

      - name: Build game
        env:
          SDL2_INCLUDE_DIR: vcpkg\installed\x64-mingw-dynamic\include
          SDL2_LIB_DIR: vcpkg\installed\x64-mingw-dynamic\lib
        run: |
          mkdir build
          mkdir build\src
          mkdir build\src\State
          $jobs = if (-not $env:NUMBER_OF_PROCESSORS) { 4 } else { $env:NUMBER_OF_PROCESSORS }
          mingw32-make "-j$jobs" CXXFLAGS="-I$env:SDL2_INCLUDE_DIR -std=gnu++1z -g -fPIE -w -MMD -MP -DSDL_MAIN_HANDLED" LDFLAGS="-L$env:SDL2_LIB_DIR -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lmpg123 -lshlwapi -lz -lpng16"

      - name: Package game
        run: |
          mkdir dist
          copy sdl2-blocks.exe dist\
          xcopy assets dist\assets\ /E /H /C /I
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_image.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_ttf.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\SDL2_mixer.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libmpg123-0.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\zlib1.dll" dist\
          copy "vcpkg\installed\x64-mingw-dynamic\bin\libpng16-16.dll" dist\
          copy "C:\mingw64\bin\libgcc_s_seh-1.dll" dist\
          copy "C:\mingw64\bin\libstdc++-6.dll" dist\
          copy "C:\mingw64\bin\libwinpthread-1.dll" dist\
          cd dist
          7z a ..\sdl2-blocks-windows.zip .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdl2-blocks-windows
          path: sdl2-blocks-windows.zip